export const APPRoutes = {
  HOME: 'home',
  DASHBOARD: 'dashboard',
  PROFILE: 'profile',
  ITEM_GROUP: 'item-group',
  SUB_CATEGORY: 'sub-category',
  PRODUCT_MASTER: 'product-master',
  PRODUCT_MASTER_UPSERT: 'product-master/upsert',
  PRODUCT_MASTER_IMPORTED: 'product-master-imported',
  PRODUCT_MASTER_IMPORTED_DETAIL: 'product-master-imported/detail',
  GST_HSN_CODE: 'gst-hsn-code',
  GST_HSN_CODE_UPSERT: 'gst-hsn-code/upsert',
  UOM: 'uom',
  ITEM: 'item',
  ITEM_ATTRIBUTE: 'item-attribute',
  STONE_FAMILY: 'stone-family',
  STONE_CLARITY: 'stone-clarity',
  STONE_SHAPE: 'stone-shape',
  STONE_DIMENSION: 'stone-dimension',
  ARCHETYPES: 'archetypes',
  ARCHETYPES_DETAIL: 'archetypes/detail',
  ARCHETYPES_EDIT: 'archetypes/edit',
  // STOCK: 'stock',
  // STOCK_ITEM: ['stock', 'item'],
  // STOCK_ITEM_GROUP: ['stock', 'item-group'],

  STOCK: {
    ROOT: 'stock',
    ITEM: 'item',
    ITEM_GROUP: 'item-group',
  },
};
