export const APPRoutes = {
  HOME: 'home',
  DASHBOARD: 'dashboard',
  PROFILE: 'profile',
  ITEM_GROUP: 'item-group',
  SUB_CATEGORY: 'sub-category',
  PRODUCT_MASTER: 'product-master',
  GST_HSN_CODE: 'gst-hsn-code',
  UOM: 'uom',
  ITEM: 'item',
  ITEM_ATTRIBUTE: 'item-attribute',
  STONE_FAMILY: 'stone-family',
  STONE_CLARITY: 'stone-clarity',
  STONE_SHAPE: 'stone-shape',
  STONE_DIMENSION: 'stone-dimension',
  STOCK: 'stock',
  STOCK_ITEM: 'stock/item',
  STOCK_ITEM_GROUP: 'stock/item-group',
};
